// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('c:/Users/gupta/Documents/react-native-project/new-app/node_modules/react');
var { Component } = React;
var ReactNative = require('c:/Users/gupta/Documents/react-native-project/new-app/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('new-app', appParameters);
});
require('c:/Users/gupta/Documents/react-native-project/new-app/index.android.js');