export const RESTORE_TOKEN = 'RESTORE_TOKEN'
export const SIGN_IN = 'SIGN_IN'
export const SIGN_OUT = 'SIGN_OUT'
export const SIGN_UP = 'SIGN_UP'
export const SET_IS_LOADING = 'SET_IS_LOADING'
export const SET_ERROR = 'SET_ERROR'

export const FETCH_CART_START = 'FETCH_CART_START'
export const FETCH_CART_SUCCEED = 'FETCH_CART_SUCCEED'
export const FETCH_CART_FAILED = 'FETCH_CART_FAILED'

export const FETCH_PAYMENT_INTENT_START = 'FETCH_PAYMENT_INTENT_START'
export const FETCH_PAYMENT_INTENT_SUCCEED = 'FETCH_PAYMENT_INTENT_SUCCEED'
export const FETCH_PAYMENT_INTENT_FAILED = 'FETCH_PAYMENT_INTENT_FAILED'

export const REGISTER_START = 'REGISTER_START'
export const REGISTER_SUCCEED = 'REGISTER_SUCCEED'
export const REGISTER_FAILED = 'REGISTER_FAILED'

export const LOGIN_START = 'LOGIN_START'
export const LOGIN_SUCCEED = 'LOGIN_SUCCEED'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const MARK_TAG_WITH_USER_START = 'MARK_TAG_WITH_USER_START'
export const MARK_TAG_WITH_USER_SUCCEED = 'MARK_TAG_WITH_USER_SUCCEED'

export const ADD_PRODUCT_TO_TAG_CART_START = 'ADD_PRODUCT_TO_TAG_CART_START'
export const ADD_PRODUCT_TO_TAG_CART_SUCCEED = 'ADD_PRODUCT_TO_TAG_CART_SUCCEED'